# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81fcf482800c9df554c517a71c9cff4eb7afbd3b34584531d2c3a900ec6841b98729971084b87905f8e1b45bdba5dad2ee9313ffe577d3208431cdda8e605eb9

test:
  secret_key_base: 5985e5e80d2996686d4e7aeb4a1fe4b5e8fc6f7a649d59dd602a4b5a349a0784ed61a52c50985e9c9408d8d8a998e9066a8d2b6c130a31f0b0f5fe1ae8e3a4ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
