# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 127a3e4182e22d5d88037ca455f7594801c9f4a26d8111dd06175e520402e592ebe0fded080cd33598b146ab4309fb10c2a47c4ecfb90a38efabb9e99ad1f3cf

test:
  secret_key_base: 471bc780df8990c63db6b6312b1acce303fe49f6adf17cf7d7e070207d14f2ed387ff9bf0d74445e11babe77f3f89aa6ae033435b66a9f781556e7d15e9275e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
